/*
 * Copyright 2017-2018 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <oqs/oqs.h>

/*
 * Certificate table information. NB: table entries must match SSL_PKEY indices
 */
static const SSL_CERT_LOOKUP ssl_cert_info [] = {
    {EVP_PKEY_RSA, SSL_aRSA}, /* SSL_PKEY_RSA */
    {EVP_PKEY_RSA_PSS, SSL_aRSA}, /* SSL_PKEY_RSA_PSS_SIGN */
    {EVP_PKEY_DSA, SSL_aDSS}, /* SSL_PKEY_DSA_SIGN */
    {EVP_PKEY_EC, SSL_aECDSA}, /* SSL_PKEY_ECC */
    {NID_id_GostR3410_2001, SSL_aGOST01}, /* SSL_PKEY_GOST01 */
    {NID_id_GostR3410_2012_256, SSL_aGOST12}, /* SSL_PKEY_GOST12_256 */
    {NID_id_GostR3410_2012_512, SSL_aGOST12}, /* SSL_PKEY_GOST12_512 */
    {EVP_PKEY_ED25519, SSL_aECDSA}, /* SSL_PKEY_ED25519 */
    {EVP_PKEY_ED448, SSL_aECDSA}, /* SSL_PKEY_ED448 */
///// OQS_TEMPLATE_FRAGMENT_GIVE_SSL_CERT_INFO_START
    {EVP_PKEY_OQS_SIG_DEFAULT, SSL_aOQS_SIG_DEFAULT}, /* SSL_PKEY_OQS_SIG_DEFAULT */
    {EVP_PKEY_P256_OQS_SIG_DEFAULT, SSL_aP256_OQS_SIG_DEFAULT}, /* SSL_PKEY_P256_OQS_SIG_DEFAULT */
    {EVP_PKEY_RSA3072_OQS_SIG_DEFAULT, SSL_aRSA3072_OQS_SIG_DEFAULT}, /* SSL_PKEY_RSA3072_OQS_SIG_DEFAULT */
    {EVP_PKEY_DILITHIUM2, SSL_aDILITHIUM2}, /* SSL_PKEY_DILITHIUM2 */
    {EVP_PKEY_P256_DILITHIUM2, SSL_aP256_DILITHIUM2}, /* SSL_PKEY_P256_DILITHIUM2 */
    {EVP_PKEY_RSA3072_DILITHIUM2, SSL_aRSA3072_DILITHIUM2}, /* SSL_PKEY_RSA3072_DILITHIUM2 */
    {EVP_PKEY_DILITHIUM3, SSL_aDILITHIUM3}, /* SSL_PKEY_DILITHIUM3 */
    {EVP_PKEY_P384_DILITHIUM3, SSL_aP384_DILITHIUM3}, /* SSL_PKEY_P384_DILITHIUM3 */
    {EVP_PKEY_DILITHIUM5, SSL_aDILITHIUM5}, /* SSL_PKEY_DILITHIUM5 */
    {EVP_PKEY_P521_DILITHIUM5, SSL_aP521_DILITHIUM5}, /* SSL_PKEY_P521_DILITHIUM5 */
    {EVP_PKEY_DILITHIUM2_AES, SSL_aDILITHIUM2_AES}, /* SSL_PKEY_DILITHIUM2_AES */
    {EVP_PKEY_P256_DILITHIUM2_AES, SSL_aP256_DILITHIUM2_AES}, /* SSL_PKEY_P256_DILITHIUM2_AES */
    {EVP_PKEY_RSA3072_DILITHIUM2_AES, SSL_aRSA3072_DILITHIUM2_AES}, /* SSL_PKEY_RSA3072_DILITHIUM2_AES */
    {EVP_PKEY_DILITHIUM3_AES, SSL_aDILITHIUM3_AES}, /* SSL_PKEY_DILITHIUM3_AES */
    {EVP_PKEY_P384_DILITHIUM3_AES, SSL_aP384_DILITHIUM3_AES}, /* SSL_PKEY_P384_DILITHIUM3_AES */
    {EVP_PKEY_DILITHIUM5_AES, SSL_aDILITHIUM5_AES}, /* SSL_PKEY_DILITHIUM5_AES */
    {EVP_PKEY_P521_DILITHIUM5_AES, SSL_aP521_DILITHIUM5_AES}, /* SSL_PKEY_P521_DILITHIUM5_AES */
    {EVP_PKEY_FALCON512, SSL_aFALCON512}, /* SSL_PKEY_FALCON512 */
    {EVP_PKEY_P256_FALCON512, SSL_aP256_FALCON512}, /* SSL_PKEY_P256_FALCON512 */
    {EVP_PKEY_RSA3072_FALCON512, SSL_aRSA3072_FALCON512}, /* SSL_PKEY_RSA3072_FALCON512 */
    {EVP_PKEY_FALCON1024, SSL_aFALCON1024}, /* SSL_PKEY_FALCON1024 */
    {EVP_PKEY_P521_FALCON1024, SSL_aP521_FALCON1024}, /* SSL_PKEY_P521_FALCON1024 */
    {EVP_PKEY_PICNICL1FULL, SSL_aPICNICL1FULL}, /* SSL_PKEY_PICNICL1FULL */
    {EVP_PKEY_P256_PICNICL1FULL, SSL_aP256_PICNICL1FULL}, /* SSL_PKEY_P256_PICNICL1FULL */
    {EVP_PKEY_RSA3072_PICNICL1FULL, SSL_aRSA3072_PICNICL1FULL}, /* SSL_PKEY_RSA3072_PICNICL1FULL */
    {EVP_PKEY_PICNIC3L1, SSL_aPICNIC3L1}, /* SSL_PKEY_PICNIC3L1 */
    {EVP_PKEY_P256_PICNIC3L1, SSL_aP256_PICNIC3L1}, /* SSL_PKEY_P256_PICNIC3L1 */
    {EVP_PKEY_RSA3072_PICNIC3L1, SSL_aRSA3072_PICNIC3L1}, /* SSL_PKEY_RSA3072_PICNIC3L1 */
    {EVP_PKEY_RAINBOWICLASSIC, SSL_aRAINBOWICLASSIC}, /* SSL_PKEY_RAINBOWICLASSIC */
    {EVP_PKEY_P256_RAINBOWICLASSIC, SSL_aP256_RAINBOWICLASSIC}, /* SSL_PKEY_P256_RAINBOWICLASSIC */
    {EVP_PKEY_RSA3072_RAINBOWICLASSIC, SSL_aRSA3072_RAINBOWICLASSIC}, /* SSL_PKEY_RSA3072_RAINBOWICLASSIC */
    {EVP_PKEY_RAINBOWICIRCUMZENITHAL, SSL_aRAINBOWICIRCUMZENITHAL}, /* SSL_PKEY_RAINBOWICIRCUMZENITHAL */
    {EVP_PKEY_P256_RAINBOWICIRCUMZENITHAL, SSL_aP256_RAINBOWICIRCUMZENITHAL}, /* SSL_PKEY_P256_RAINBOWICIRCUMZENITHAL */
    {EVP_PKEY_RSA3072_RAINBOWICIRCUMZENITHAL, SSL_aRSA3072_RAINBOWICIRCUMZENITHAL}, /* SSL_PKEY_RSA3072_RAINBOWICIRCUMZENITHAL */
    {EVP_PKEY_RAINBOWICOMPRESSED, SSL_aRAINBOWICOMPRESSED}, /* SSL_PKEY_RAINBOWICOMPRESSED */
    {EVP_PKEY_P256_RAINBOWICOMPRESSED, SSL_aP256_RAINBOWICOMPRESSED}, /* SSL_PKEY_P256_RAINBOWICOMPRESSED */
    {EVP_PKEY_RSA3072_RAINBOWICOMPRESSED, SSL_aRSA3072_RAINBOWICOMPRESSED}, /* SSL_PKEY_RSA3072_RAINBOWICOMPRESSED */
    {EVP_PKEY_RAINBOWIIICLASSIC, SSL_aRAINBOWIIICLASSIC}, /* SSL_PKEY_RAINBOWIIICLASSIC */
    {EVP_PKEY_P384_RAINBOWIIICLASSIC, SSL_aP384_RAINBOWIIICLASSIC}, /* SSL_PKEY_P384_RAINBOWIIICLASSIC */
    {EVP_PKEY_RAINBOWIIICIRCUMZENITHAL, SSL_aRAINBOWIIICIRCUMZENITHAL}, /* SSL_PKEY_RAINBOWIIICIRCUMZENITHAL */
    {EVP_PKEY_P384_RAINBOWIIICIRCUMZENITHAL, SSL_aP384_RAINBOWIIICIRCUMZENITHAL}, /* SSL_PKEY_P384_RAINBOWIIICIRCUMZENITHAL */
    {EVP_PKEY_RAINBOWIIICOMPRESSED, SSL_aRAINBOWIIICOMPRESSED}, /* SSL_PKEY_RAINBOWIIICOMPRESSED */
    {EVP_PKEY_P384_RAINBOWIIICOMPRESSED, SSL_aP384_RAINBOWIIICOMPRESSED}, /* SSL_PKEY_P384_RAINBOWIIICOMPRESSED */
    {EVP_PKEY_RAINBOWVCLASSIC, SSL_aRAINBOWVCLASSIC}, /* SSL_PKEY_RAINBOWVCLASSIC */
    {EVP_PKEY_P521_RAINBOWVCLASSIC, SSL_aP521_RAINBOWVCLASSIC}, /* SSL_PKEY_P521_RAINBOWVCLASSIC */
    {EVP_PKEY_RAINBOWVCIRCUMZENITHAL, SSL_aRAINBOWVCIRCUMZENITHAL}, /* SSL_PKEY_RAINBOWVCIRCUMZENITHAL */
    {EVP_PKEY_P521_RAINBOWVCIRCUMZENITHAL, SSL_aP521_RAINBOWVCIRCUMZENITHAL}, /* SSL_PKEY_P521_RAINBOWVCIRCUMZENITHAL */
    {EVP_PKEY_RAINBOWVCOMPRESSED, SSL_aRAINBOWVCOMPRESSED}, /* SSL_PKEY_RAINBOWVCOMPRESSED */
    {EVP_PKEY_P521_RAINBOWVCOMPRESSED, SSL_aP521_RAINBOWVCOMPRESSED}, /* SSL_PKEY_P521_RAINBOWVCOMPRESSED */
    {EVP_PKEY_SPHINCSHARAKA128FROBUST, SSL_aSPHINCSHARAKA128FROBUST}, /* SSL_PKEY_SPHINCSHARAKA128FROBUST */
    {EVP_PKEY_P256_SPHINCSHARAKA128FROBUST, SSL_aP256_SPHINCSHARAKA128FROBUST}, /* SSL_PKEY_P256_SPHINCSHARAKA128FROBUST */
    {EVP_PKEY_RSA3072_SPHINCSHARAKA128FROBUST, SSL_aRSA3072_SPHINCSHARAKA128FROBUST}, /* SSL_PKEY_RSA3072_SPHINCSHARAKA128FROBUST */
    {EVP_PKEY_SPHINCSSHA256128FROBUST, SSL_aSPHINCSSHA256128FROBUST}, /* SSL_PKEY_SPHINCSSHA256128FROBUST */
    {EVP_PKEY_P256_SPHINCSSHA256128FROBUST, SSL_aP256_SPHINCSSHA256128FROBUST}, /* SSL_PKEY_P256_SPHINCSSHA256128FROBUST */
    {EVP_PKEY_RSA3072_SPHINCSSHA256128FROBUST, SSL_aRSA3072_SPHINCSSHA256128FROBUST}, /* SSL_PKEY_RSA3072_SPHINCSSHA256128FROBUST */
    {EVP_PKEY_SPHINCSSHAKE256128FROBUST, SSL_aSPHINCSSHAKE256128FROBUST}, /* SSL_PKEY_SPHINCSSHAKE256128FROBUST */
    {EVP_PKEY_P256_SPHINCSSHAKE256128FROBUST, SSL_aP256_SPHINCSSHAKE256128FROBUST}, /* SSL_PKEY_P256_SPHINCSSHAKE256128FROBUST */
    {EVP_PKEY_RSA3072_SPHINCSSHAKE256128FROBUST, SSL_aRSA3072_SPHINCSSHAKE256128FROBUST}, /* SSL_PKEY_RSA3072_SPHINCSSHAKE256128FROBUST */
///// OQS_TEMPLATE_FRAGMENT_GIVE_SSL_CERT_INFO_END
};
